import { Inter } from 'next/font/google'
import './globals.css'
import { NavBar } from './components/NavBar/NavBar'
import { Footer } from './components/Footer/Footer'
import { Container } from './components/Container/Container'
import { SectionPage } from './components/SectionPage/SectionPage'
import { Contact } from './components/Contact/Contact'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Domki Mazurskie',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <div className="bg-slate-100"> 
          <Container>
            <SectionPage
              header="📨 Kontakt"
              subheader="Skontaktuj się z nami w celu rezerwacji domku!"
            >
              <Contact />
            </SectionPage>
          </Container>
        </div>
        <Footer/>
      </body>
    </html>
  )
}
